CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    address VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    balance DECIMAL(12,2) DEFAULT 0,
    seller BOOLEAN DEFAULT FALSE
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    category VARCHAR(255) NOT NULL,
    long_description VARCHAR(1000000) NOT NULL,
    image_link VARCHAR(255) NOT NULL,
    creator INT NOT NULL REFERENCES Users(id), 
    rating DECIMAL(2,1)
);

CREATE TABLE Inventory (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL 
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Users(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    quantity INT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT FALSE,
    time_fulfilled timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Cart ( 
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL
);

CREATE TABLE Coupons (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    discount INT NOT NULL,
    users VARCHAR(255)
);

CREATE TABLE Orders ( 
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    oid INT NOT NULL,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Users(id),
    time_fulfilled timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    quantity INT NOT NULL,
    time_created timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    status BOOLEAN NOT NULL,
    cid INT REFERENCES Coupons(id)
);

CREATE TABLE Reviews ( 
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rating INT NOT NULL,
    content VARCHAR(255),
    review_time timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),  
    uid INT NOT NULL REFERENCES Users(id), 
    rid INT NOT NULL,
    is_seller BOOLEAN NOT NULL
);

CREATE TABLE Votes ( 
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    rid INT NOT NULL REFERENCES Reviews(id),
    vote INT NOT NULL
);

CREATE TABLE Refunds ( 
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    oid INT NOT NULL REFERENCES Orders(id),
    uid INT NOT NULL REFERENCES Users(id),
    sid INT NOT NULL REFERENCES Users(id),
    reason VARCHAR(255),
    value DECIMAL(12,2) NOT NULL,
    status BOOLEAN NOT NULL
);


